import React from "react";
import {
  Card,
  CardHeader,
  CardMedia,
  CardTitle,
  CardText
} from "material-ui/Card";
import Paper from "material-ui/Paper";
import basic from "../basic.jpg";
const DisplayContent = props => {
  const { currentPixel } = props;
  let month = "";
  let p_u = currentPixel.pixel_unique;
  const Parr = p_u.toString().split("");
  const convertmonth = () => {
    Parr.length > 3
      ? (month = Parr.slice(0, 2).join(""))
      : (month = Parr.slice(0, 1).join(""));
  };
  convertmonth();
  const date = p_u - month * 100;
  const day = date === 1 ? "Monday" : null;
  return (
    <div className="DisplayContent">
      <Card className>
        <div className="DisplayContent_top">
          <CardMedia overlay={<CardTitle title="haven't added any event" />}>
            {currentPixel.img ? (
              <img src={currentPixel.img} alt="myImage.jpg" />
            ) : (
              <img src={basic} alt="defaultimage.jpg" />
            )}
          </CardMedia>
        </div>
        <div className="DisplayContent_bottom">
          <div className="DisplayContent_left">
            <CardHeader
              title={`${month}月 ${date}日 2018`}
              subtitle={day}
              avatar="https://thumbs.dreamstime.com/b/pixel-art-style-rainbow-homosexual-heart-sign-71899821.jpg"
            />
            <CardText>{currentPixel.text}</CardText>
          </div>
          <div className="DisplayContent_right">
            <div className="DisplayContent_Quote">
              random quote that is generated by tags gonna be displayed in this
              div
            </div>
          </div>
        </div>
      </Card>
      <Paper zDepth={2}>
        <p>
          {props.quote[0]
            ? props.quote[0].text
            : "You haven't added any quote in this pixel"}
        </p>
        <p>{props.quote[0] ? `-By ${props.quote[0].author}` : null}</p>
      </Paper>
    </div>
  );
};

export default DisplayContent;
