import React from "react";
import heart from "../heart.png";
import {
  Card,
  CardActions,
  CardHeader,
  CardMedia,
  CardTitle,
  CardText
} from "material-ui/Card";
import * as moment from "moment";
import basic from "../basic.jpg";
const DisplayContent = props => {
  const { currentPixel } = props;
  let month = "";
  console.log(currentPixel);
  let p_u = currentPixel.pixel_unique;
  const Parr = p_u.toString().split("");
  const convertmonth = () => {
    Parr.length > 3
      ? (month = Parr.slice(0, 2).join(""))
      : (month = Parr.slice(0, 1).join(""));
  };
  convertmonth();
  const date = p_u - month * 100;
  const day = date === 1 ? "Monday" : null;
  return (
    <div className="DisplayContent">
      <Card className="card">
        <div className="DisplayContent_top">
          <CardMedia
            overlay={<CardTitle title="wheather icon" subtitle="weather" />}
          >
            {currentPixel.img ? (
              <img src={currentPixel.img} alt="image.jpg" />
            ) : (
              <img src={basic} alt="defaultimage.jpg" />
            )}
          </CardMedia>
        </div>
        <div className="DisplayContent_bottom">
          <div className="DisplayContent_left">
            <CardHeader
              title={`${month}月 ${date}日 2018`}
              subtitle={day}
              avatar={heart}
            />
            <CardText>{currentPixel.text}</CardText>
          </div>
          <div className="DisplayContent_right">
            <div className="Quote">
              random quote that is generated by tags gonna be displayed in this
              div
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default DisplayContent;
